packages:
  - packages/**

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - sharp
  - workerd

catalogs:
  mcp:
    "@modelcontextprotocol/sdk": 1.13.0
    "@hono/mcp": 0.1.0
  dev:
    "@types/node": 24.2.1
    "@virtual-live-lab/eslint-config": 2.2.22
    "@virtual-live-lab/prettier-config": 2.0.19
    "@virtual-live-lab/tsconfig": 2.1.20
    eslint: 9.29.0
    eslint-plugin-react-hooks: 5.2.0
    pkg-pr-new: 0.0.53
    prettier: 3.5.3
    release-it: 19.0.3
    release-it-pnpm: 4.6.6
    typescript: 5.8.3
    typescript-eslint: 8.34.1
  react:
    "@types/react": 19.1.8
    "@types/react-dom": 19.1.6
    react: 19.1.0
    react-dom: 19.1.0
