name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  paths-filter:
    name: Changed Paths Filter
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 5
    outputs:
      cloudflare: ${{ steps.filter.outputs.cloudflare }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            cloudflare:
              - 'packages/cloudflare/**'

  ci:
    name: Code Problem Check
    runs-on: ubuntu-24.04
    needs: paths-filter
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Setup Node.js and pnpm
        uses: ./.github/workflows/composite/setup

      - name: Build
        run: pnpm run build

      - name: Run ESLint
        run: pnpm run lint

      - name: Run Prettier
        run: pnpm run format:ci

      - name: Run typecheck
        run: pnpm run typecheck

      - name: Run tests
        run: pnpm run test

      - name: Run knip
        run: pnpm run knip

      - name: Build cloudflare
        if: needs.paths-filter.outputs.cloudflare == 'true'
        run: pnpm --filter cloudflare run build

      - name: Run Prettier on cloudflare
        if: needs.paths-filter.outputs.cloudflare == 'true'
        run: pnpm --filter cloudflare run format:ci

      - name: Run typecheck on cloudflare
        if: needs.paths-filter.outputs.cloudflare == 'true'
        run: pnpm --filter cloudflare run typecheck
